server {
    listen 80 ; 
    server_name example.com; 

    # 获取真实IP
    real_ip_recursive on; 
    set_real_ip_from 0.0.0.0/0; 
    real_ip_header X-Forwarded-For; 

    # CORS
    add_header Access-Control-Allow-Origin * always; 
    add_header Access-Control-Allow-Methods GET,POST always; 
    if ( $request_method = 'OPTIONS' ) {
        return 204; 
    }

    # 处理API
    location ~ ^/(api|test|pc|pe)\.php(/|$) {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000; # 对应Docker-compose中的端口 
        set $real_script_name $fastcgi_script_name; 
    }

    # 其他请求
    location / {
        return 404; 
    }
}
